version: "3.8"

services:
  nginx:
    image: nginx:1.25-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./frontend/build:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - public

  backend:
    build: ./backend
    restart: always
    env_file: ./backend/.env
    environment:
      - DATABASE_URL=sqlite:////data/data.db
      - APP_ENV=production
    volumes:
      - ./data/sqlite:/data
    expose:
      - "8000"
    networks:
      - public

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    entrypoint: ""
    networks:
      - public

networks:
  public:
    driver: bridge
